# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];
  boot = {

    initrd.availableKernelModules =
      [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_usb_sdmmc" ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
    resumeDevice = "/dev/disk/by-uuid/c13e9d86-8a11-4138-a5d4-f97e28927cc3";
  };
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/3a8697ab-b878-4d7b-be9a-f91b4c048d67";
      fsType = "ext4";
    };

    "/mnt/Storage" = {
      device = "/dev/disk/by-uuid/a31edd82-945f-448f-98d3-70d2afbe7d39";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/A36E-CABF";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/c13e9d86-8a11-4138-a5d4-f97e28927cc3"; }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.bluetooth.enable = true;

  # sleep and hibernate
  powerManagement.enable = true;
  services.logind.settings.Login.LidSwitch = "suspend-then-hibernate";
  systemd.sleep.extraConfig = ''
    HibernateDelaySec=30m
    SuspendState=mem
  '';
}
